### ISSUE TITLE
App showing  giving  java.lang.RuntimeException: Unknown animation name: objectAnimator when clicked on cardview item

### ISSUE THREAD

**Issue by klaus19** [klaus19/Labas#8]
When I click on upper left image icon so my card can move to left for a second and come , I get  following error in my code. 

Its in ImageAdapter and the xml file is item_image.xml

`Process: com.example.visuallithuanian, PID: 12501
                                                                                                    java.lang.RuntimeException: Unknown animation name: objectAnimator
                                                                                                    	at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:194)
                                                                                                    	at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:182)
                                                                                                    	at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:158)
                                                                                                    	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:139)
                                                                                                    	at com.example.visuallithuanian.adapter.ImageAdapter.onBindViewHolder(ImageAdapter.kt:41)
                                                                                                    	at com.example.visuallithuanian.adapter.ImageAdapter.onBindViewHolder(ImageAdapter.kt:15)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
                                                                                                    	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
                                                                                                    	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
                                                                                                    	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
                                                                                                    	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
                                                                                                    	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
                                                                                                    	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
2023-02-08 15:51:02.316 12501-12501 AndroidRuntime          com.example.visuallithuanian         E  	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:761)
                                                                                                    	at android.view.View.measure(View.java:25833)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3676)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2460)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2739)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:780)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)`

**Comment by klaus19** [comment]
The error is solved after making changes in item_imaage.xml. I was not having only one parentview for Scrollview and also in my ImageAdapter I hadn't created ObjectAnimator.
